<?php

namespace ContainerVHAFPHM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lu02MrcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lu02Mrc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Lu02Mrc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'appointmentRepository' => ['privates', 'App\\Repository\\AppointmentRepository', 'getAppointmentRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'planningRepository' => ['privates', 'App\\Repository\\PlanningRepository', 'getPlanningRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.Lu02Mrc.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.Lu02Mrc": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'appointmentRepository' => 'App\\Repository\\AppointmentRepository',
            'em' => '?',
            'planningRepository' => 'App\\Repository\\PlanningRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
