<?php

namespace ContainerVHAFPHM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CIssjexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cIssjex' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cIssjex'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'planning' => ['privates', '.errored..service_locator.cIssjex.App\\Entity\\Planning', NULL, 'Cannot autowire service ".service_locator.cIssjex": it needs an instance of "App\\Entity\\Planning" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'planning' => 'App\\Entity\\Planning',
        ]);
    }
}
