<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRgxddya\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRgxddya/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerRgxddya.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerRgxddya\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerRgxddya\App_KernelProdContainer([
    'container.build_hash' => 'Rgxddya',
    'container.build_id' => 'f9849008',
    'container.build_time' => 1739706388,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRgxddya');
