<?php

namespace ContainerHvZrj12;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K1TjEmUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k1TjEmU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k1TjEmU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'planningRepository' => ['privates', 'App\\Repository\\PlanningRepository', 'getPlanningRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.k1TjEmU.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.k1TjEmU": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'planningRepository' => 'App\\Repository\\PlanningRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
