knp_snappy:
  pdf:
    enabled: true
    binary: '"C:/Program Files/wkhtmltopdf/bin/wkhtmltopdf.exe"' # Guillemets autour du chemin
    options:
      encoding: 'utf-8'
      margin-top: 10
      margin-bottom: 10
      margin-left: 10
      margin-right: 10
