<?php

namespace ContainerCxvjKEi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCourService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.OMNEaQD.App\Entity\Cour' shared service.
     *
     * @return \App\Entity\Cour
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.OMNEaQD": it needs an instance of "App\\Entity\\Cour" but this type has been excluded in "config/services.yaml".');
    }
}
