<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVHAFPHM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVHAFPHM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVHAFPHM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVHAFPHM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVHAFPHM\App_KernelDevDebugContainer([
    'container.build_hash' => 'VHAFPHM',
    'container.build_id' => '67d3309f',
    'container.build_time' => 1740133798,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVHAFPHM');
